### ISSUE TITLE
Ability to add/remove lightness

### ISSUE THREAD

**Issue by alex-prime-one** [inVoltag/figma-ui-color-palette#3]
Sometimes I need a lot more shades of one color than 10. Please provide ability to add/remove lightnesses.
By default you can have what you already implemented (50-900) and by clicking plus icon you should add one more knob (1000) to the lightness scale. Maybe you need to set some limitations on how many new lightnesses can be created (24 for example).
Also need to design a way of deleting them. Maybe it can be keyboard button + click. Or some UI element. Need to think on it.

**Comment by inVoltag** [comment]
The plugin helps build color themes by declining brand colors in different tints. The good practice is to make a color palette with few declinations (~10) to turn these tints into semantic colors, applied through an application/service (via its design system). The 50-900 model has been provided by [Material Design](https://material.io/design/color/the-color-system.html#color-theme-creation) and it is currently used for creating color system. The plugin has been built for that usage, help people build color system. Adding tints can be challenging because the limitation is important to keep a dry and operable color palette, because it must be used as semantic colors.
I could add intermediate scales: 50, 100, 150, 200, 250 … 850, 900.

**Comment by alex-prime-one** [comment]
Or dropdown for switching presets:
10 (Material design)
13 (Ant design)
19 (Atlassian)
24 (Super ultimate palette :)

**Comment by alex-prime-one** [comment]
Probably no matter how you call it

**Comment by inVoltag** [comment]
OK I see, thanks for your insight. The idea of having presets looks interesting 😉

**Comment by alex-prime-one** [comment]
it looks amazing, exactly what I need. Thank you for your work, waiting for the official release.

**Comment by inVoltag** [comment]
The plugin has been released 😉
