### ISSUE TITLE
Color not added to the range

### ISSUE THREAD

**Issue by Flexiflooze** [inVoltag/figma-ui-color-palette#83]
My brand's color (that I give at the beginning) is not added to the range (shows up next to the range without any attributes). 
Is there a solution for that ?
![UI Color Palette﹒Material Design 50-900 (Google)﹒Palette](https://github.com/inVoltag/figma-ui-color-palette/assets/137519477/c547784a-e1ef-44d1-973a-6eea3d4a8ce9)

**Comment by inVoltag** [comment]
Hello @Flexiflooze,
Due to the LCH color space, the source color (which are the brand colors) would not be included into the shades.
The plugin has already included since the version 19 an acknowledgment that indicates the shade with a thin distance from its source color.
We plan for the next version a better color space management that may resolve the problem. We could notify you when it will be deployed.

**Comment by inVoltag** [comment]
Hello @Flexiflooze,
I released an updated version where you can select a different color space. I suggest you to select the HSL color space to include your source colors within the palette. Nevertheless, the HSL color space is not recommended for accessibility and efficient contrast. Here is the [release note](https://uicp.link/whats-new). Tell me if it works for you.
